import React from "react";
import {
  DesktopOutlined,
  PieChartOutlined,
  FileOutlined,
  TeamOutlined,
  UserOutlined,
  ProfileOutlined,
  SearchOutlined,
  AppstoreOutlined,
  MailOutlined,
  MenuUnfoldOutlined,
  MenuFoldOutlined,
  LoginOutlined,
  LogoutOutlined,
  NotificationOutlined,
  DownOutlined,
  ZoomInOutlined,
  ZoomOutOutlined,
  CarOutlined,
  HomeOutlined,
  InfoOutlined,
} from "@ant-design/icons";

export let IconsSet = {
  User: "User",
  Profile: "Profile",
  Search: "Search",
  Desktop: "Desktop",
  PieChart: "PieChart",
  File: "File",
  Team: "Team",
  AppStore: "AppStore",
  Mail: "Mail",
  MenuF: "MenuF",
  MenuU: "MenuU",
  Login: "Login",
  Logout: "Logout",
  Notification: "Notification",
  Down: "Down",
  ZoomIn: "ZoomIn",
  ZoomOut: "ZoomOut",
  Car: "Car",
  Home: "Home",
  InfoOut: "InfoOut",
};

export let IconsMap = new Map([
  ["User", <UserOutlined />],
  ["Profile", <ProfileOutlined />],
  ["Search", <SearchOutlined />],
  ["Desktop", <DesktopOutlined />],
  ["PieChart", <PieChartOutlined />],
  ["File", <FileOutlined />],
  ["Team", <TeamOutlined />],
  ["AppStore", <AppstoreOutlined />],
  ["Mail", <MailOutlined />],
  ["MenuF", <MenuFoldOutlined />],
  ["MenuU", <MenuUnfoldOutlined />],
  ["Login", <LoginOutlined />],
  ["Logout", <LogoutOutlined />],
  ["Notification", <NotificationOutlined />],
  ["Down", <DownOutlined />],
  ["ZoomIn", <ZoomInOutlined />],
  ["ZoomOut", <ZoomOutOutlined />],
  ["Car", <CarOutlined />],
  ["Home", <HomeOutlined />],
  ["InfoOut", <InfoOutlined />],
]);
